name: Test screen-ocr on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use the latest macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify a compatible Python version

      - name: Install screen-ocr from GitHub
        run: pip install git+https://github.com/wolfmanstout/screen-ocr.git@optimize-screen-capture

      - name: Run test_screenshot_performance.py
        run: python test_screenshot_performance.py
